<a href="https://colab.research.google.com/github/zeeboi9/stablevicuna_notmine/blob/main/pytorch_fundumentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [37]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [38]:
# scaler tensor
scalar =torch.tensor(6)
scalar

tensor(6)

In [39]:
scalar.ndim

0

In [40]:
scalar.item()

6

In [41]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [42]:
vector.ndim

1

In [43]:
vector.shape

torch.Size([2])

In [44]:
#matrix
matrix=torch.tensor([[5, 6],
                     [7, 8]])
matrix

tensor([[5, 6],
        [7, 8]])

In [45]:
matrix.ndim

2

In [46]:
matrix[1]

tensor([7, 8])

In [47]:
matrix.shape

torch.Size([2, 2])

In [48]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [6, 7, 8]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [49]:
tensor.ndim


3

In [50]:
tensor.shape

torch.Size([1, 3, 3])

In [51]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [52]:
#random tensors
#random tensors are important because of the way that many neural networks learn is that they start with tensors full of random numbers and then adjust thos random numbers to better reprsent the given data
#start with random numbers -> look at data -> updtae random numbers _. look at data-> update random numbers


In [53]:
# create random numbers give it size
rand_tens=torch.rand(10, 5,)
print(rand_tens)
rand_tens.ndim


tensor([[0.0773, 0.3937, 0.9086, 0.2488, 0.9221],
        [0.3695, 0.6023, 0.6032, 0.2281, 0.0639],
        [0.1891, 0.1757, 0.4099, 0.9300, 0.8558],
        [0.6913, 0.8895, 0.8969, 0.6493, 0.8234],
        [0.8699, 0.7015, 0.9297, 0.1027, 0.1046],
        [0.3930, 0.1933, 0.4825, 0.8578, 0.4937],
        [0.4494, 0.4824, 0.6541, 0.1383, 0.2765],
        [0.4469, 0.5776, 0.6732, 0.3427, 0.4368],
        [0.4947, 0.8511, 0.9718, 0.6292, 0.8769],
        [0.7487, 0.6753, 0.7735, 0.4254, 0.5112]])


2

In [54]:
#make random tensor with a similar shape to a image tensor
rist=torch.rand(size=(224, 224, 3))#hight, width, color channel(red green blue)
rist.shape
rist.ndim

3

In [55]:
#create tensor with all zeros
z=torch.zeros(size=(3, 4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
o=torch.ones(size=(3, 4))
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ghe=torch.arange(0, 10)
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [58]:
#creating tensors like
trunk=torch.zeros_like(input=ghe)
trunk

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
#tensor datatypes
#float32 tensor
f32t=torch.tensor([3.0, 6.0, 9.0],
                  dtype=None, #what data type e.g float32 or float16 or float64 the number is how many bitshte higher the number the more presision
                  device=None,#device your tensor is on
                  requires_grad=False)
f32t

tensor([3., 6., 9.])

note tensor data type is one of the 3 biggest error that are commenly run into during deep learning with pytorch

1.   tensor is no the right dtata type
2.   List itemtenor is not the right shap
3.   tensor is not on the right device



In [60]:
f32t.dtype

torch.float32

In [61]:
f16t=f32t.type(torch.float16)
f16t

tensor([3., 6., 9.], dtype=torch.float16)

In [62]:
f16t*f32t

tensor([ 9., 36., 81.])

In [63]:
int32=torch.tensor([3, 6, 9], dtype=torch.int32)
int32


int32=torch.tensor([3, 6, 9], dtype=torch.long)
int32

tensor([3, 6, 9])

In [64]:
f32t+int32

tensor([ 6., 12., 18.])

In [65]:
#getting info from tensor

#    tensor is no the right dtata type -- to get data type from tensor use "tensor.dtype"
#    List itemtenor is not the right shap -- to get shape of tensor use "tensor.shape"
#    tensor is not on the right device -- to get device tensor is on use "tensor.device"


In [66]:
# create a tensor and get their attributes
scp=torch.rand(3, 4)
print(scp)
print(f'tensor device: {scp.device}')
print(f'tensor shape: {scp.shape}')
print(f'tensor dimensions: {scp.ndim}')
print(f'tensor data type: {scp.dtype}')

tensor([[0.7226, 0.5121, 0.3928, 0.0159],
        [0.4780, 0.5445, 0.9335, 0.9071],
        [0.1968, 0.6376, 0.4592, 0.5290]])
tensor device: cpu
tensor shape: torch.Size([3, 4])
tensor dimensions: 2
tensor data type: torch.float32


In [67]:
#element wise multiplication
trunip=torch.tensor([1, 2, 3])
rump=torch.tensor([1, 2, 3])
trunip
rump
print(trunip, "*", rump)
print(f'equals:{rump*trunip}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [68]:
#matriz multiplication
torch.matmul(rump,rump)

tensor(14)

In [77]:
## finding the min max mean sum of a tensor
## torch.mean function needs float 32 or float dtype to work
x=torch.arange(0, 100, 10)
x.min()
x.type(torch.float32).mean()
x.max()
x.sum()

tensor(90)